#!/bin/bash

let nfailed=0

# general test
../orient.py -tx 1.0 -ty -0.7 -tz 0.2 -rx 75 -ry 40 -rz -60 test.xyz > general/output.xyz
DIFF=$(diff -b general/output.xyz general/reference.xyz)
if [ "$DIFF" != "" ]; then
  echo 'General test failed!'
  let nfailed+=1
fi

# principle axes test
../orient.py -op test.xyz > principle/output.xyz
DIFF=$(diff -b principle/output.xyz principle/reference.xyz)
if [ "$DIFF" != "" ]; then
  echo 'Principle test failed!'
  let nfailed+=1
fi

# align test
../orient.py -a 1 2 3 test.xyz > align/output.xyz
DIFF=$(diff -b align/output.xyz align/reference.xyz)
if [ "$DIFF" != "" ]; then
  echo 'Align test failed!'
  let nfailed+=1
fi

if [ $nfailed -eq 0 ]; then
  echo 'All tests passed!'
else
  echo "$nfailed tests failed."
fi
